ProjectWebsite/ProjectWebsite/Controllers/ProductTypeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjectWebsite.Models;

namespace ProjectWebsite.Controllers
{
    public class ProductTypeController : Controller
    {
        private ProductManagementContext db = new ProductManagementContext();

        /// <summary>
        /// Xem, thêm, xóa, sửa loại sản phẩm...
        /// Author: Phan thanh tú (18/07/2021)
        /// </summary>
        /// <param name="type"></param>
        /// <returns></returns>
        public ActionResult Index()
        {
            if (Session["TaiKhoanAdmin"] == null)
            {
                return RedirectToAction("Login", "Admin");
            }
            else
            {
                return View(db.PRODUCT_TYPE.ToList());
            }
        }

        // GET: ProductType/Create
        public ActionResult Create()
        {
            if (Session["TaiKhoanAdmin"] == null)
            {
                return RedirectToAction("Login", "Admin");
            }
            else
            {
                return View();
            }
        }

        // POST: ProductType/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Type,TypeName")] PRODUCT_TYPE pRODUCT_TYPE)
        {
            if (Session["TaiKhoanAdmin"] == null)
            {
                return RedirectToAction("Login", "Admin");
            }
            else
            {
                if (pRODUCT_TYPE.TypeName != null)
                {
                    db.PRODUCT_TYPE.Add(pRODUCT_TYPE);
                    db.SaveChanges();
                    TempData["Message"] = "Thêm Thành công";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["Message"] = "Thất Bại";
                    return View(pRODUCT_TYPE);
                }

            }
        }

        // GET: ProductType/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["TaiKhoanAdmin"] == null)
            {
                return RedirectToAction("Login", "Admin");
            }
            else
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                PRODUCT_TYPE pRODUCT_TYPE = db.PRODUCT_TYPE.Find(id);
                if (pRODUCT_TYPE == null)
                {
                    return HttpNotFound();
                }
                return View(pRODUCT_TYPE);
            }
        }

        // POST: ProductType/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Type,TypeName")] PRODUCT_TYPE pRODUCT_TYPE)
        {
            if (Session["TaiKhoanAdmin"] == null)
            {
                return RedirectToAction("Login", "Admin");
            }
            else
            {
                if (pRODUCT_TYPE.TypeName != null)
                {
                    db.Entry(pRODUCT_TYPE).State = EntityState.Modified;
                    db.SaveChanges();
                    TempData["Message"] = "Cập nhật thành công";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["Message"] = "Thất Bại";
                    return View(pRODUCT_TYPE);
                }

            }
        }

        // GET: ProductType/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["TaiKhoanAdmin"] == null)
            {
                return RedirectToAction("Login", "Admin");
            }
            else
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                PRODUCT_TYPE pRODUCT_TYPE = db.PRODUCT_TYPE.Find(id);
                if (pRODUCT_TYPE == null)
                {
                    return HttpNotFound();
                }
                return View(pRODUCT_TYPE);
            }
        }

        // POST: ProductType/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (Session["TaiKhoanAdmin"] == null)
            {
                return RedirectToAction("Login", "Admin");
            }
            else
            {
                PRODUCT_TYPE pRODUCT_TYPE = db.PRODUCT_TYPE.Find(id);
                db.PRODUCT_TYPE.Remove(pRODUCT_TYPE);
                db.SaveChanges();
                TempData["Message"] = "Xóa thành công";
                return RedirectToAction("Index");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjectWebsite/ProjectWebsite/Views/ProductType/Create.cshtml
@model ProjectWebsite.Models.PRODUCT_TYPE

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/Layout_Admin.cshtml";
}

@*Thông báo*@
<script src="~/Scripts/Admin/js/jquery.js"></script>
<link href="~/assets/toastr-master/toastr.css" rel="stylesheet" />
<script src="~/assets/toastr-master/toastr.js"></script>
@*Toastr*@
<section id="main-content">
    <section class="wrapper site-min-height">
        <div class="row">
            <span id="Message" class="hidden">@TempData["Message"]</span>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="col-lg-4">
                    <div class="form-horizontal">
                        <h4>Thêm mới loại sản phẩm</h4>
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            <div class="col-md-10">
                                <label>Nhập loại sản phẩm:</label>
                            </div>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.TypeName, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.TypeName, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-10">
                                <input type="submit" value="Thêm mới" class="btn btn-success" />
                                <a class="btn btn-success" href="@Url.Action("Index","ProductType")" style="margin-left:10px">Quay lại</a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </section>
</section>
<script type="text/javascript">
    $(document).ready(function () {
        var message = $('#Message').text();
        if (message === 'Thất Bại') {
            toastr.warning('Vui lòng nhập đầy đủ thông tin');
        }
    });
</script>

ProjectWebsite/ProjectWebsite/Views/ProductType/Delete.cshtml
@model ProjectWebsite.Models.PRODUCT_TYPE

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/Layout_Admin.cshtml";
}

<section id="main-content">
    <section class="wrapper site-min-height">
        <div class="row">
            <span id="Message" class="hidden">@TempData["Message"]</span>
            <div class="col-lg-4">
                <h4>Bạn có chắc chắn muốn xóa?</h4>
            </div>
            <div class="col-md-10">
                <label>Mã loại:</label>
            </div>
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Type)
            </div>
            <div class="col-md-10">
                <label>Tên loại:</label>
            </div>
            <div class="col-md-10">
                @Html.DisplayFor(model => model.TypeName)
            </div>
            <div class="col-md-10">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Xóa loại" style="margin-top:10px" class="btn btn-success" />
                        <a class="btn btn-success" style="margin-top:10px;margin-left:10px" href="@Url.Action("Index","ProductType")">Quay lại</a>
                    </div>
                }
            </div>
        </div>
    </section>
</section>

ProjectWebsite/ProjectWebsite/Views/ProductType/Edit.cshtml
@model ProjectWebsite.Models.PRODUCT_TYPE

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/Layout_Admin.cshtml";
}
@*Thông báo*@
<script src="~/Scripts/Admin/js/jquery.js"></script>
<link href="~/assets/toastr-master/toastr.css" rel="stylesheet" />
<script src="~/assets/toastr-master/toastr.js"></script>
@*Toastr*@
<section id="main-content">
    <section class="wrapper site-min-height">
        <div class="row">
            <span id="Message" class="hidden">@TempData["Message"]</span>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="col-lg-4">
                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Type)

                        <div class="form-group">
                            <div class="col-md-10">
                                <label>Nhập loại sản phẩm:</label>
                            </div>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.TypeName, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.TypeName, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-10">
                                <input type="submit" value="Cập nhật" class="btn btn-success" />
                                <a class="btn btn-success" href="@Url.Action("Index","ProductType")" style="margin-left:10px">Quay lại</a>
                            </div>
                        </div>
                    </div>
                </div>

            }
        </div>
    </section>
</section>
<script type="text/javascript">
    $(document).ready(function () {
        var message = $('#Message').text();
        if (message === 'Thất Bại') {
            toastr.warning('Trường tên loại không được bỏ trống!');
        }
    });
</script>

ProjectWebsite/ProjectWebsite/Views/ProductType/Index.cshtml
@model IEnumerable<ProjectWebsite.Models.PRODUCT_TYPE>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout_Admin.cshtml";
}

<section id="main-content">
    <section class="wrapper site-min-height">
        <div class="row">
            <span id="Message" class="hidden">@TempData["Message"]</span>
            <div class="col-lg-12">
                <div class="col-lg-12">
                    <h4 style="text-align:center;margin-bottom: 20px;color:red;font-size:30px;font-weight:bold"> QUẢN LÝ LOẠI MẶT HÀNG </h4>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="col-lg-12">
                    <section class="panel">
                        <header class="panel-heading" style="color:black;font-weight:bold">
                            Dữ liệu loại mặt hàng

                        </header>
                        <div class="col-lg-8">
                            <a class="btn btn-success" href="@Url.Action("Create","ProductType") " style="margin-bottom:20px"> Thêm mới</a>
                        </div>
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th style="color:black;font-weight:bold;text-align:center">MÃ LOẠI</th>
                                    <th style="color:black;font-weight:bold;text-align:center">TÊN LOẠI</th>
                                    <th style="color:black;font-weight:bold;text-align:center">CHỨC NĂNG</th>
                                </tr>
                            </thead>
                            @foreach (var item in Model)
                            {
                                <tbody>
                                    <tr>
                                        <td style="color:black;text-align:center">@item.Type</td>
                                        <td style="color:black;text-align:center">@item.TypeName</td>
                                        <td style="text-align: center;">
                                            <a class="btn btn-danger" href="@Url.Action("Delete","ProductType",new { id = item.Type})" style=" margin-left: 20px;">Xóa loại <i class="fa fa-trash-o"></i></a>
                                            <a class="btn btn-info" href="@Url.Action("Edit","ProductType",new { id = item.Type})" style=" margin-left: 20px;">Cập nhật <i class="fa fa-pencil"></i></a>
                                        </td>
                                    </tr>
                                </tbody>
                            }

                        </table>
                    </section>
                </div>
            </div>
        </div>
    </section>
</section>