ProjectWebsite/ProjectWebsite/Models/PRODUCT_SALE.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_SALE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT_SALE()
        {
            this.PRODUCT = new HashSet<PRODUCT>();
        }
    
        public int Sale { get; set; }
        public int SaleName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT> PRODUCT { get; set; }
    }
}

ProjectWebsite/ProjectWebsite/Controllers/ProductSaleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjectWebsite.Models;

namespace ProjectWebsite.Controllers
{
    public class ProductSaleController : Controller
    {
        private ProductManagementContext db = new ProductManagementContext();

        // GET: ProductSale
        public ActionResult Index()
        {
            if (Session["TaiKhoanAdmin"] == null)
            {
                return RedirectToAction("Login", "Admin");
            }
            else
            {
                return View(db.PRODUCT_SALE.ToList());
            }
        }

        // GET: ProductSale/Create
        public ActionResult Create()
        {
            if (Session["TaiKhoanAdmin"] == null)
            {
                return RedirectToAction("Login", "Admin");
            }
            else
            {
                return View();
            }
        }

        // POST: ProductSale/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Sale,SaleName")] PRODUCT_SALE pRODUCT_SALE)
        {
            if (Session["TaiKhoanAdmin"] == null)
            {
                return RedirectToAction("Login", "Admin");
            }
            else
            {
                if (pRODUCT_SALE.SaleName != 0)
                {
                    db.PRODUCT_SALE.Add(pRODUCT_SALE);
                    db.SaveChanges();
                    TempData["Message"] = "Thêm Thành công";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["Message"] = "Thất Bại";
                    return View(pRODUCT_SALE);
                }
                
            }
        }

        // GET: ProductSale/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["TaiKhoanAdmin"] == null)
            {
                return RedirectToAction("Login", "Admin");
            }
            else
            {

                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                PRODUCT_SALE pRODUCT_SALE = db.PRODUCT_SALE.Find(id);
                if (pRODUCT_SALE == null)
                {
                    return HttpNotFound();
                }
                return View(pRODUCT_SALE);
            }
        }

        // POST: ProductSale/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Sale,SaleName")] PRODUCT_SALE pRODUCT_SALE)
        {
            if (Session["TaiKhoanAdmin"] == null)
            {
                return RedirectToAction("Login", "Admin");
            }
            else
            {

                if (pRODUCT_SALE.SaleName != 0)
                {
                    db.Entry(pRODUCT_SALE).State = EntityState.Modified;
                    db.SaveChanges();
                    TempData["Message"] = "Cập nhật thành công";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["Message"] = "Thất Bại";
                    return View(pRODUCT_SALE);
                }
                
            }
        }

        // GET: ProductSale/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["TaiKhoanAdmin"] == null)
            {
                return RedirectToAction("Login", "Admin");
            }
            else
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                PRODUCT_SALE pRODUCT_SALE = db.PRODUCT_SALE.Find(id);
                if (pRODUCT_SALE == null)
                {
                    return HttpNotFound();
                }
                return View(pRODUCT_SALE);
            }
        }

        // POST: ProductSale/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (Session["TaiKhoanAdmin"] == null)
            {
                return RedirectToAction("Login", "Admin");
            }
            else
            {
                PRODUCT_SALE pRODUCT_SALE = db.PRODUCT_SALE.Find(id);
                db.PRODUCT_SALE.Remove(pRODUCT_SALE);
                db.SaveChanges();
                TempData["Message"] = "Xóa thành công";
                return RedirectToAction("Index");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjectWebsite/ProjectWebsite/Views/ProductSale/Create.cshtml
@model ProjectWebsite.Models.PRODUCT_SALE

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/Layout_Admin.cshtml";
}
@*Thông báo*@
<script src="~/Scripts/Admin/js/jquery.js"></script>
<link href="~/assets/toastr-master/toastr.css" rel="stylesheet" />
<script src="~/assets/toastr-master/toastr.js"></script>
@*Toastr*@
<section id="main-content">
    <section class="wrapper site-min-height">
        <div class="row">
            <span id="Message" class="hidden">@TempData["Message"]</span>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="col-lg-4">
                    <div class="form-horizontal">
                        <h4>Thêm mới khuyến mãi</h4>
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            <div class="col-md-10">
                                <label>Nhập trị giá khuyến mãi:</label>
                            </div>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.SaleName, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.SaleName, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-10">
                                <input type="submit" value="Thêm mới" class="btn btn-success" />
                                <a class="btn btn-success" href="@Url.Action("Index","ProductSale")" style="margin-left:10px">Quay lại</a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </section>
</section>
<script type="text/javascript">
    $(document).ready(function () {
        var message = $('#Message').text();
        if (message === 'Thất Bại') {
            toastr.warning('Vui lòng nhập đầy đủ thông tin');
        }
    });
</script>

ProjectWebsite/ProjectWebsite/Views/ProductSale/Delete.cshtml
@model ProjectWebsite.Models.PRODUCT_SALE

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/Layout_Admin.cshtml";
}

<section id="main-content">
    <section class="wrapper site-min-height">
        <div class="row">
            <span id="Message" class="hidden">@TempData["Message"]</span>
            <div class="col-lg-4">
                <h4>Bạn có chắc chắn muốn xóa?</h4>
            </div>
            <div class="col-md-10">
                <label>Mã khuyến mãi:</label>
            </div>
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Sale)
            </div>
            <div class="col-md-10">
                <label>Trị giá khuyến mãi:</label>
            </div>
            <div class="col-md-10">
                @Html.DisplayFor(model => model.SaleName)
            </div>
            <div class="col-md-10">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Xóa ngay" style="margin-top:10px" class="btn btn-success" />
                        <a class="btn btn-success" style="margin-top:10px;margin-left:10px" href="@Url.Action("Index","ProductBrand")">Quay lại</a>
                    </div>
                }
            </div>
        </div>
    </section>
</section>

ProjectWebsite/ProjectWebsite/Views/ProductSale/Edit.cshtml
@model ProjectWebsite.Models.PRODUCT_SALE

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/Layout_Admin.cshtml";
}

@*Thông báo*@
<script src="~/Scripts/Admin/js/jquery.js"></script>
<link href="~/assets/toastr-master/toastr.css" rel="stylesheet" />
<script src="~/assets/toastr-master/toastr.js"></script>
@*Toastr*@
<section id="main-content">
    <section class="wrapper site-min-height">
        <div class="row">
            <span id="Message" class="hidden">@TempData["Message"]</span>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="col-lg-4">
                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Sale)

                        <div class="form-group">
                            <div class="col-md-10">
                                <label>Nhập trị giá khuyến mãi:</label>
                            </div>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.SaleName, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.SaleName, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-10">
                                <input type="submit" value="Cập nhật" class="btn btn-success" />
                                <a class="btn btn-success" href="@Url.Action("Index","ProductSale")" style="margin-left:10px">Quay lại</a>
                            </div>
                        </div>
                    </div>
                </div>

            }
        </div>
    </section>
</section>
<script type="text/javascript">
    $(document).ready(function () {
        var message = $('#Message').text();
        if (message === 'Thất Bại') {
            toastr.warning('Trường tên thương hiệu không được bỏ trống!');
        }
    });
</script>

ProjectWebsite/ProjectWebsite/Views/ProductSale/Index.cshtml
@model IEnumerable<ProjectWebsite.Models.PRODUCT_SALE>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout_Admin.cshtml";
}
<section id="main-content">
    <section class="wrapper site-min-height">
        <div class="row">
            <span id="Message" class="hidden">@TempData["Message"]</span>
            <div class="col-lg-12">
                <div class="col-lg-12">
                    <h4 style="text-align:center;margin-bottom: 20px;color:red;font-size:30px;font-weight:bold"> QUẢN LÝ KHUYẾN MÃI </h4>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="col-lg-12">
                    <section class="panel">
                        <header class="panel-heading" style="color:black;font-weight:bold">
                            Dữ liệu khuyến mãi

                        </header>
                        <div class="col-lg-8">
                            <a class="btn btn-success" href="@Url.Action("Create","ProductSale") " style="margin-bottom:20px"> Thêm mới</a>
                        </div>
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th style="color:black;font-weight:bold;text-align:center">MÃ KHUYẾN MÃI</th>
                                    <th style="color:black;font-weight:bold;text-align:center">TRỊ GIÁ</th>
                                    <th style="color:black;font-weight:bold;text-align:center">CHỨC NĂNG</th>
                                </tr>
                            </thead>
                            @foreach (var item in Model)
                            {
                                <tbody>
                                    <tr>
                                        <td style="color:black;text-align:center">@item.Sale</td>
                                        <td style="color:black;text-align:center">@item.SaleName</td>
                                        <td style="text-align: center;">
                                            <a class="btn btn-danger" href="@Url.Action("Delete","ProductSale",new { id = item.Sale})" style=" margin-left: 20px;">Xóa ngay <i class="fa fa-trash-o"></i></a>
                                            <a class="btn btn-info" href="@Url.Action("Edit","ProductSale",new { id = item.Sale})" style=" margin-left: 20px;">Cập nhật <i class="fa fa-pencil"></i></a>
                                        </td>
                                    </tr>
                                </tbody>
                            }

                        </table>
                    </section>
                </div>
            </div>
        </div>
    </section>
</section>